spring:
  application:
    name: spring-flux
  profiles:
    active: dev

server:
  port: 8099

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/reactive_db
    username: bsafe
    password: bsafe
