spring:
  application:
    name: spring-flux
  profiles:
    active: dev

server:
  port: 8099

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: POSTGRESQL
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_db
    username: bsafe
    password: bsafe
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
  data:
    r2dbc:
      repositories.enabled: true
