
### GET ALL
GET {{apiUrl}}/route/profiles

### GET ONE
GET {{apiUrl}}/route/profiles/1

### Create profile
POST {{apiUrl}}/route/profiles

{
    "email": "email1@domain.com"
}

### GET ALL
GET {{apiUrl}}/sse/profiles
Content-Type:text/event-stream
